workbenchparts-master/routes/web.php
<?php

Route::redirect('/', '/workbench');

Route::get('/workbench', 'PageController@workbench');
Route::get('/expense', 'PageController@expense');
Route::get('/display', 'PageController@display');

Route::get('/cart/store/{store}', 'CartItemController@index');
Route::post('/cartItem', 'CartItemController@store');
Route::patch('/cartItem/{cartItem}', 'CartItemController@update');
Route::delete('/cartItem/{cartItem}', 'CartItemController@destroy');

Route::get('/requestItem/store/{store}', 'RequestItemController@index');
Route::post('/requestItem', 'RequestItemController@store');

Route::get('/order/store/{store}', 'OrderController@index');
Route::get('/order/{order}', 'OrderController@show');
Route::post('/order', 'OrderController@store');

workbenchparts-master/app/Store.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    protected $connection = 'ibmi';
    protected $table = 'imcmpyfl';
    public $incrementing = false;
    public $timestamps = false;

    public static function openLampsBrickLocations()
    {
        return self::select('lploc', 'mpadr1', 'mpcity', 'mpstte', 'mpzpcd')
            ->join('lpctrlfl', function($join) {
                $join->on('lploc', '=', 'mploc#')
                    ->on('lpcmpy', '=', 'mpcmp#');
            })
            ->where('lpcmpy', '02')
            ->where('lpstyp', 'B')
            ->where('lpclosed', '0')
            ->get();
    }

    public function getCityAttribute()
    {
        return ucwords(strtolower($this->mpcity));
    }
}

workbenchparts-master/resources/views/partials/addToCartModal.blade.php
<div class="modal fade" id="addToCartModal" role="dialog" aria-labelledby="addToCartModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addToCartModalTitle">Add Item to Cart</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="add-form-action" action="/cartItem" method="POST">
                @csrf
                <input type="hidden" class="skuModalInput" name="sku" value="">
                <input type="hidden" class="storeModalInput" name="store" value="">
                <div class="modal-body">
                    <div class="d-flex justify-content-center">
                        <div class="d-flex flex-column">
                            <h1 class="text-center mb-0" class="modalTitle"></h1>
                            <p class="text-center text-muted mt-0" class="modalDescription"></p>
                            <img src="" class="modalImg">
                            <div class="form-group row mt-4">
                                <label class="col-sm-8 col-form-label font-weight-bold" for="modalQuantity">Quantity:</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-control-lg text-center modalQuantity" name="quantity" value="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Confirm</button>
                </div>
            </form>
        </div>    
    </div>
</div>

workbenchparts-master/resources/views/partials/flashMessages.blade.php
@if ($errors->any())
    <div class="alert alert-danger alert-dismissible border border-danger shadow-lg flash-message p-5" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <ul class="m-0 list-unstyled">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('message'))
    <div class="alert alert-success alert-dismissible border border-success shadow-lg flash-message p-5" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ session()->get('message') }}
    </div>
@endif

workbenchparts-master/resources/views/partials/requestItemModal.blade.php
<div class="modal fade" id="requestItemModal" role="dialog" aria-labelledby="requestItemModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border border-warning">
            <div class="modal-header">
                <h5 class="modal-title" id="addToCartModalTitle">Request Item</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="add-form-action" action="/requestItem" method="POST">
                @csrf
                <input type="hidden" class="skuModalInput" name="sku" value="">
                <input type="hidden" class="storeModalInput" name="store" value="">
                <div class="modal-body">
                    <div class="d-flex justify-content-center">
                        <div class="d-flex flex-column">
                            <h1 class="text-center mb-0" class="modalTitle"></h1>
                            <p class="text-center text-muted mt-0" class="modalDescription"></p>
                            <img src="" class="modalImg">
                            <p class="px-3 mt-3">
                                <i class="material-icons text-warning">warning</i>
                                <span class="ml-1">
                                    This item has a sku status which prevents it from being ordered here.
                                </span>
                            </p>
                            <p class="px-3">
                                Would you like to submit a request for this item?
                            </p> 
                            <div class="form-group row mt-4">
                                <label class="col-sm-8 col-form-label font-weight-bold" for="modalQuantity">Requested Quantity:</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control form-control-lg text-center modalQuantity" id="modalQuantity" name="quantity" value="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Confirm</button>
                </div>
            </form>
        </div>    
    </div>
</div>

workbenchparts-master/resources/views/partials/storeSelectionModal.blade.php
<div class="modal fade" id="storeSelectionModal" role="dialog" aria-labelledby="storeSelectionModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addToCartModalTitle">Select Store</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="store-select-action">
                <div class="modal-body">
                    <div class="d-flex justify-content-center">
                        <div class="d-flex flex-column">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label font-weight-bold" for="store">Store:</label>
                                <div class="col-sm-9" style="flex: 1 1 auto;">
                                    <select class="form-control" id="store-select-input" name="store">
                                        @foreach($stores as $store)
                                            <option value="{{$store->lploc}}">{{$store->lploc}} {{$store->city}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Confirm</button>
                </div>
            </form>
        </div>    
    </div>
</div>